version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - mvn install
  build:
    commands:
      - echo "Building the JAR files..."
      - mvn clean package
      - echo "Renaming appspec-renamed.yml to appspec.yml"
      - mv appspec-renamed.yml appspec.yml
  post_build:
    commands:
      - echo "Build completed successfully."
      - ls target/
      - pwd
artifacts:
  files:
    - target/my-java-project-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
  name: build_$(date +%Y-%m-%d)/JavaApp
